FROM node:16-alpine
WORKDIR '/app'
COPY ./package.json ./
RUN npm install
RUN mkdir -p node_modules/.cache/.eslintcache && chmod 777 -R node_modules/.cache/.eslintcache
COPY . .
CMD ["npm", "run", "start"]